### ISSUE TITLE
Issue with altair dependancy

### ISSUE THREAD

**Issue by RomitChakraborty** [alejandro-ao/ask-multiple-pdfs#23]
I get the following error when I try streamlit run app.py:

Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/usr/local/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/usr/local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/usr/local/lib/python3.8/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

My altair installation is up to date. 
pip3 install --upgrade altair 
Requirement already up-to-date: altair in /usr/local/lib/python3.8/site-packages (5.0.1)
Requirement already satisfied, skipping upgrade: jinja2 in /usr/local/lib/python3.8/site-packages (from altair) (2.11.3)
Requirement already satisfied, skipping upgrade: pandas>=0.18 in /usr/local/lib/python3.8/site-packages (from altair) (1.1.4)
Requirement already satisfied, skipping upgrade: typing-extensions>=4.0.1; python_version < "3.11" in /usr/local/lib/python3.8/site-packages (from altair) (4.7.1)
Requirement already satisfied, skipping upgrade: toolz in /usr/local/lib/python3.8/site-packages (from altair) (0.12.0)
Requirement already satisfied, skipping upgrade: jsonschema>=3.0 in /usr/local/lib/python3.8/site-packages (from altair) (3.2.0)
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib/python3.8/site-packages (from altair) (1.19.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from jinja2->altair) (1.1.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/site-packages (from pandas>=0.18->altair) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.8/site-packages (from pandas>=0.18->altair) (2020.4)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /usr/local/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (20.3.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /usr/local/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (0.17.3)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.8/site-packages (from jsonschema>=3.0->altair) (49.2.0)
Requirement already satisfied, skipping upgrade: six>=1.11.0 in /Users/romit.chakraborty/Library/Python/3.8/lib/python/site-packages (from jsonschema>=3.0->altair) (1.15.0)

Is there something else that I am missing?

**Comment by aabalke33** [comment]
The current release, Altair 5.0.1, breaks functionality. Try "pip install altair<5" to install a previous version. I had the same problem and version 4.2.2 worked for me.

**Comment by RomitChakraborty** [comment]
Awesome. Works now!
